# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    cooldown:
      semver-major-days: 5
      semver-minor-days: 5
      semver-patch-days: 5

    commit-message:
      prefix: meta
    open-pull-requests-limit: ${{secrets.OPEN_PR_LIMIT}}

  - package-ecosystem: npm
    directory: /tools/eslint
    schedule:
      interval: monthly
    cooldown:
      semver-major-days: 5
      semver-minor-days: 5
      semver-patch-days: 5
    commit-message:
      prefix: tools
    open-pull-requests-limit: ${{secrets.OPEN_PR_LIMIT}}
    groups:
      eslint:
        applies-to: version-updates
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /tools/lint-md
    schedule:
      interval: monthly
    cooldown:
      semver-major-days: 5
      semver-minor-days: 5
      semver-patch-days: 5
    commit-message:
      prefix: tools
    open-pull-requests-limit: ${{secrets.OPEN_PR_LIMIT}}
    groups:
      lint-md:
        applies-to: version-updates
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /tools/doc
    schedule:
      interval: weekly
    cooldown:
      semver-major-days: 5
      semver-minor-days: 5
      semver-patch-days: 5
    commit-message:
      prefix: tools
    open-pull-requests-limit: ${{secrets.OPEN_PR_LIMIT}}
    groups:
      doc:
        applies-to: version-updates
        patterns:
          - '*'
