language: cpp
sudo: false
cache: ccache
os: linux
matrix:
  include:
    - name: "Linter"
      language: node_js
      node_js: "node"
      env:
        - NODE=$(which node)
      script:
        - make lint
        # Lint the first commit in the PR.
        - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then
            bash tools/lint-pr-commit-message.sh ${TRAVIS_PULL_REQUEST} || true;
          fi
    - name: "Test Suite"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      install:
        - export CC='ccache gcc-4.9' CXX='ccache g++-4.9' JOBS=2
        - ./configure
        - make -j2 V=
      script:
        - PARALLEL_ARGS='--flaky-tests=skip' make -j1 test
