blank_issues_enabled: true
contact_links:
  - name: â‰ï¸ Need general help with Node.js?
    url: https://github.com/nodejs/help
    about: Please file an issue in our help repo.
  - name: ğŸ“¦ Have an issue with npm?
    url: https://github.com/npm/cli/issues
    about: npm has a seperate issue tracker.
  - name: ğŸ“¡ Have an issue with undici? (`WebSocket`, `fetch`, etc.)
    url: https://github.com/nodejs/undici/issues
    about: Undici has a seperate issue tracker.
  - name: ğŸŒ Found a problem with nodejs.org beyond the API reference docs?
    url: https://github.com/nodejs/nodejs.org/issues/new/choose
    about: Please file an issue in the Node.js website repo.
