[workspace]
resolver = "2"
members = [
    "provider",
    "temporal_capi",
    "zoneinfo",

    # Tools
    "tools/*",
]

[workspace.package]
edition = "2021"
version = "0.1.0"
rust-version = "1.82.0"
authors = ["boa-dev"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/boa-dev/temporal"
readme = "./README.md"
exclude = [
    "docs/*",
    ".github/*",
    "debug/",
    ".gitignore",
    "CONTRIBUTING.md",
    "cliff.toml",
    "tests/data/zoneinfo64.res",
]

[workspace.dependencies]
# Self
temporal_rs = { version = "~0.1.0", path = ".", default-features = false }
timezone_provider = { version = "~0.1.0", path = "./provider" }
zoneinfo_rs = { version = "~0.0.17", path = "./zoneinfo" }

# Dependencies
tinystr = "0.8.1"
icu_calendar = { version = "2.0.3", default-features = false }
icu_locale = "2.0.0"
rustc-hash = "2.1.0"
num-traits = { version = "0.2.19", default-features = false }
ixdtf = "0.6.0"
iana-time-zone = "0.1.64"
log = "0.4.28"
tzif = "0.4.0"
jiff-tzdb = "0.1.4"
combine = "4.6.7"
web-time = "1.1.0"
zerovec = "0.11.4"
zoneinfo64 = "0.2.0"

# Diplomat
diplomat-tool = { version = "0.13.0", default-features = false }
diplomat-runtime = { version = "0.13.0", default-features = false }
diplomat = { version = "0.13.0", default-features = false }


[package]
name = "temporal_rs"
keywords = ["date", "time", "calendar", "timezone", "duration"]
categories = ["date-and-time", "internationalization"]
description = "Temporal in Rust is an implementation of the TC39 Temporal Builtin Proposal in Rust."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme.workspace = true
exclude.workspace = true

[dependencies]

core_maths = "0.1.1"
icu_calendar = { workspace = true, features = ["compiled_data"] }
icu_locale.workspace = true
ixdtf = { workspace = true, features = ["duration"] }
num-traits.workspace = true
tinystr.workspace = true
writeable = "0.6.1"

# log feature
log = { workspace = true, optional = true }

# tzdb feature
timezone_provider = { workspace = true }

# System time feature
web-time = { workspace = true, optional = true }
iana-time-zone = { workspace = true, optional = true }

[dev-dependencies]
timezone_provider = { workspace = true, features = ["zoneinfo64"] }
zoneinfo64 = { workspace = true }
resb = "0.1.0"

[features]
default = ["sys"]
log = ["dep:log"]
compiled_data = ["tzdb"]
sys = ["std", "compiled_data", "dep:web-time", "dep:iana-time-zone"]
tzdb = [
    "std",
    "timezone_provider/tzif",
]
std = []

[package.metadata.cargo-all-features]
denylist = ["default"]
max_combination_size = 4

[package.metadata.docs.rs]
all-features = true
