# need to declare the language as well as the matrix below
language: node_js

os:
  - windows

node_js:
  - 12
  - 10
  - 8
  - 6

env: "DEPLOY_VERSION=testing"

install:
  - "node . install"

script:
  - "node . run tap -- \"test/tap/*.js\" -t600 -Rclassic -c"
