language: node_js
node_js:
  - iojs
  - "0.12"
  - "0.10"
  - "0.8"
env:
  - DEPLOY_VERSION=testing
before_install:
  - "npm config set spin false"
  - "npm install -g npm/npm#2.x"
  - "sudo mkdir -p /var/run/couchdb"
script: "npm run-script test-all"
notifications:
    slack: npm-inc:kRqQjto7YbINqHPb1X6nS3g8
