name: CI

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 13
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: ./configure && make -j2
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 13
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Environment Information
        run: npx envinfo
      - name: Install deps
        run: choco install nasm
      - name: Build
        run: ./vcbuild.bat
  build-macOS:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 13
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: ./configure && make -j8
  lint-addon-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Lint addon docs
      run: NODE=$(which node) make lint-addon-docs
  lint-cpp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint C/C++ files
      run: make lint-cpp
  lint-md:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Lint docs
      run: NODE=$(which node) make lint-md
  lint-js:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Lint JavaScript files
      run: NODE=$(which node) make lint-js
