name: CI

on: [pull_request]

jobs:
  lint-commit-message:
    name: "First commit message adheres to guidelines at <a href=\"https://goo.gl/p2fr5Q\">https://goo.gl/p2fr5Q</a>"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "First commit message adheres to guidelines at <a href=\"https://goo.gl/p2fr5Q\">https://goo.gl/p2fr5Q</a>"
        language: node_js
        node_js: "node"
        script:
          bash -x tools/lint-pr-commit-message.sh ${{ github.event.number }}
