name: Comment on issues and PRs when labeled
on:
  issues:
    types: [labeled]
  pull_request_target:
    types: [labeled]

env:
  STALE_MESSAGE: >
    This issue/PR was marked as stalled, it will be automatically closed in 30 days.
    If it should remain open, please leave a comment explaining why it should remain open.
  FAST_TRACK_MESSAGE: Fast-track has been requested by @${{ github.actor }}. Please üëç to approve.
  NOTABLE_CHANGE_MESSAGE: The notable-changes label has been added by @${{ github.actor }}.
    Please include your text below if you'd like to include a more detailed summary in the changelog.
    ```
    [Insert here]
    ```

permissions:
  contents: read

jobs:
  stale-comment:
    permissions:
      issues: write
      pull-requests: write
    if: github.repository == 'nodejs/node' && github.event.label.name == 'stalled'
    runs-on: ubuntu-latest
    steps:
      - name: Post stalled comment
        env:
          NUMBER: ${{ github.event.issue.number || github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh issue comment "$NUMBER" --repo ${{ github.repository }} --body "$STALE_MESSAGE"

  fast-track:
    permissions:
      pull-requests: write
    if: github.repository == 'nodejs/node' && github.event_name == 'pull_request_target' && github.event.label.name == 'fast-track'
    runs-on: ubuntu-latest
    steps:
      - name: Request Fast-Track
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr comment ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --body "$FAST_TRACK_MESSAGE"

  notable-change:
    permissions:
      pull-requests: write
    if: github.repository == 'nodejs/node' && github.event_name == 'pull_request_target' && github.event.label.name == 'notable-change'
    runs-on: ubuntu-latest
    steps:
      - name: Add notable change description
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr comment ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --body "$NOTABLE_CHANGE_MESSAGE"
