name: Coverage Windows

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - lib/**/*.js
      - vcbuild.bat
      - src/**/*.cc
      - src/**/*.h
      - test/**
      - tools/gyp/**
      - tools/test.py
      - .github/workflows/coverage-windows.yml
      - codecov.yml
      - .nycrc
  push:
    branches:
      - main
    paths:
      - lib/**/*.js
      - vcbuild.bat
      - src/**/*.cc
      - src/**/*.h
      - test/**
      - tools/gyp/**
      - tools/test.py
      - .github/workflows/coverage-windows.yml
      - codecov.yml
      - .nycrc

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.12'
  FLAKY_TESTS: keep_retrying

permissions:
  contents: read

jobs:
  coverage-windows:
    if: github.event.pull_request.draft == false
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: false
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install deps
        run: choco install nasm
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: ./vcbuild.bat
      # TODO(bcoe): investigate tests that fail with coverage enabled
      # on Windows.
      - name: Test
        run: ./vcbuild.bat test-ci-js; node -e 'process.exit(0)'
        env:
          NODE_V8_COVERAGE: ./coverage/tmp
      - name: Report
        run: npx c8 report
        env:
          NODE_OPTIONS: --max-old-space-size=8192
      - name: Clean tmp
        run: npx rimraf ./coverage/tmp
      - name: Upload
        uses: codecov/codecov-action@13ce06bfc6bbe3ecf90edbbf1bc32fe5978ca1d3  # v5.3.1
        with:
          directory: ./coverage
