name: Coverage Windows

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - lib/**/*.js
      - Makefile
      - src/**/*.cc
      - src/**/*.h
      - test/**
      - tools/gyp/**
      - tools/test.py
      - .github/workflows/coverage-windows.yml
      - codecov.yml
  push:
    branches:
      - main
    paths:
      - lib/**/*.js
      - Makefile
      - src/**/*.cc
      - src/**/*.h
      - test/**
      - tools/gyp/**
      - tools/test.py
      - .github/workflows/coverage-windows.yml
      - codecov.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.12'
  FLAKY_TESTS: keep_retrying

permissions:
  contents: read

jobs:
  coverage-windows:
    if: github.event.pull_request.draft == false
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
        with:
          persist-credentials: false
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d  # v5.1.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install deps
        run: choco install nasm
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: ./vcbuild.bat
      # TODO(bcoe): investigate tests that fail with coverage enabled
      # on Windows.
      - name: Test
        run: ./vcbuild.bat test-ci-js; node -e 'process.exit(0)'
        env:
          NODE_V8_COVERAGE: ./coverage/tmp
      - name: Report
        run: npx c8 report
        env:
          NODE_OPTIONS: --max-old-space-size=8192
      - name: Clean tmp
        run: npx rimraf ./coverage/tmp
      - name: Upload
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673  # v4.5.0
        with:
          directory: ./coverage
          token: ${{ secrets.CODECOV_TOKEN }}
