name: Node.js daily job

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

env:
  NODE_VERSION: lts/*

permissions:
  contents: read

jobs:
  build-lto:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: false
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6  # v4.0.4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Build lto
        run: |
          sudo apt-get update && sudo apt-get install ninja-build -y
          ./configure --enable-lto --ninja
          ninja -C out/Release
