name: Node.js daily job

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

env:
  NODE_VERSION: lts/*

permissions:
  contents: read

jobs:
  build-lto:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # v4.2.0
        with:
          persist-credentials: false
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b  # v4.0.3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Build lto
        run: |
          sudo apt-get update && sudo apt-get install ninja-build -y
          ./configure --enable-lto --ninja
          ninja -C out/Release
