name: Find inactive TSC voting members

on:
  schedule:
    # Run every Tuesday 12:05 AM UTC.
    - cron: 5 0 * * 2

  workflow_dispatch:

env:
  NODE_VERSION: lts/*

permissions:
  contents: read

jobs:
  find:
    if: github.repository == 'nodejs/node'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # v3.6.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Clone nodejs/TSC repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # v3.6.0
        with:
          fetch-depth: 0
          path: .tmp
          persist-credentials: false
          repository: nodejs/TSC

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8  # v3.7.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Find inactive TSC voting members
        run: tools/find-inactive-tsc.mjs >> $GITHUB_ENV

      - name: Open pull request
        uses: gr2m/create-or-update-pull-request-action@77596e3166f328b24613f7082ab30bf2d93079d5
        # Creates a PR or update the Action's existing PR, or
        # no-op if the base branch is already up-to-date.
        env:
          GITHUB_TOKEN: ${{ secrets.GH_USER_TOKEN }}
        with:
          author: Node.js GitHub Bot <github-bot@iojs.org>
          branch: actions/inactive-tsc
          body: |
            This PR was generated by tools/find-inactive-tsc.yml.

            @nodejs/tsc ${{ env.INACTIVE_TSC_HANDLES }}

            ${{ env.DETAILS_FOR_COMMIT_BODY }}
          commit-message: 'meta: move TSC voting member(s) to regular member(s)'
          labels: meta
          title: 'meta: move TSC voting member(s) to regular member(s)'
          update-pull-request-title-and-body: true
