name: Find inactive TSC members

on:
  schedule:
    # Run every Tuesday 12:05 AM UTC.
    - cron: 5 0 * * 2

  workflow_dispatch:

env:
  NODE_VERSION: lts/*

jobs:
  find:
    if: github.repository == 'nodejs/node'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Clone nodejs/TSC repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: .tmp
          persist-credentials: false
          repository: nodejs/TSC

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Find inactive TSC members
        run: tools/find-inactive-tsc.mjs >> $GITHUB_ENV

      - name: Open pull request
        uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_USER_TOKEN }}
        with:
          author: Node.js GitHub Bot <github-bot@iojs.org>
          branch: actions/inactive-tsc
          body: |
            This PR was generated by tools/find-inactive-tsc.yml.

            @nodejs/tsc ${{ env.INACTIVE_TSC_HANDLES }}

            ${{ env.DETAILS_FOR_COMMIT_BODY }}
          commit-message: 'meta: move one or more TSC members to emeritus'
          labels: meta
          title: 'meta: move one or more TSC members to emeritus'
