name: Test internet

on:
  workflow_dispatch:
  schedule:
    - cron: 5 0 * * *

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - .github/workflows/test-internet.yml
      - test/internet/**
      - internal/dns/**
      - lib/dns.js
      - lib/net.js
  push:
    branches:
      - main
      - canary
      - v[0-9]+.x-staging
      - v[0-9]+.x
    paths:
      - .github/workflows/test-internet.yml
      - test/internet/**
      - internal/dns/**
      - lib/dns.js
      - lib/net.js

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.12'
  FLAKY_TESTS: keep_retrying
  CC: clang
  CXX: clang++

permissions:
  contents: read

jobs:
  test-internet:
    if: github.repository == 'nodejs/node' || github.event_name != 'schedule'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
        with:
          persist-credentials: false
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d  # v5.1.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: make build-ci -j4 V=1 CONFIG_FLAGS="--error-on-warn"
      - name: Test Internet
        run: make test-internet -j4 V=1;
