name: V8 patch update
on:
  schedule:
    # Run once a week at 00:05 AM UTC on Sunday.
    - cron: 5 0 * * 0
  workflow_dispatch:

env:
  NODE_VERSION: lts/*

permissions:
  contents: read

jobs:
  v8-update:
    if: github.repository == 'nodejs/node'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # v3.6.0
        with:
          persist-credentials: false
      - name: Cache node modules and update-v8
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8  # v3.3.1
        id: cache-v8-npm
        env:
          cache-name: cache-v8-npm
        with:
          path: |
            ~/.update-v8
            ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install Node.js
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8  # v3.7.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install node-core-utils
        run: npm install -g node-core-utils@latest
      - name: Check and download new V8 version
        run: |
            ./tools/dep_updaters/update-v8-patch.sh > temp-output
            cat temp-output
            tail -n1 temp-output | grep "NEW_VERSION=" >> "$GITHUB_ENV" || true
            rm temp-output
      - uses: gr2m/create-or-update-pull-request-action@77596e3166f328b24613f7082ab30bf2d93079d5
        # Creates a PR or update the Action's existing PR, or
        # no-op if the base branch is already up-to-date.
        env:
          GITHUB_TOKEN: ${{ secrets.GH_USER_TOKEN }}
        with:
          author: Node.js GitHub Bot <github-bot@iojs.org>
          body: This is an automated patch update of V8 to ${{ env.NEW_VERSION }}.
          branch: actions/update-v8-patch  # Custom branch *just* for this Action.
          labels: v8 engine
          title: 'deps: patch V8 to ${{ env.NEW_VERSION }}'
          update-pull-request-title-and-body: true
